version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - recantonet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./api
    container_name: recanto-api
    ports:
      - "${API_PORT}:8081"    
    environment:
      API_PORT: ${API_PORT}
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - recantonet

  web:
    build:
      context: ./web
    container_name: recanto-web
    environment:
      WEB_PORT: ${WEB_PORT}
      API_URL: http://api:8081/api/
    ports:
      - "${WEB_PORT}:8080"
    depends_on:
      - api
    networks:
      - recantonet

volumes:
  mysql_data:

networks:
  recantonet:
