# Conexão com o banco
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Configurações do Broker MQTT
mqtt.broker.url=${MQTT_URL}
mqtt.broker.username=${MQTT_USERNAME}
mqtt.broker.password=${MQTT_PASSWORD}
mqtt.broker.client-id=${MQTT_CLIENTID}
mqtt.broker.topic=${MQTT_TOPIC}

# Porta customizada da API
server.port=8081